// Generated by Wrangler by running `wrangler types ./types/wrangler.d.ts`

interface Env {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	COOKIE_SECRET: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
